site_name: Freakshow Documents

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy

nav:

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra_css:
  - styles.css